Addition is one of the easiest operation to carry out. The same hold true for matrices. Two matrices can be added only if they have the same dimensions. The elements at similar positions get added.

Given two matrices A and B having (n1 x m1) and (n2 x m2) dimensions respectively. Add A and B. 

Example 1:

Input:
n1 = 2, m1 = 3
A[][] = {{1, 2, 3},
         {4, 5, 6}}

n2 = 2, m2 = 3
B[][] = {{1, 3, 3},
         {2, 3, 3}}

Output: 2 5 6 6 8 9
Explanation:
The summation matrix of A and B is:
res[][] = {{2, 5, 6},
           {6, 8, 9}}
The output is generated by traversing each
row sequentially.
Example 2:

Input:
n1 = 3, m1 = 2
A[][] = {{1, 2},
         {3, 4}, 
         {5, 6}}

n2 = 3, m2 = 2
B[][] = {{1, 3},
          {3, 2},
         {3, 3}}
Output: 2 5 6 6 8 9
 

Your Task:
You dont need to read input or print anything. Complete the function sumMatrix() that takes A and B as input parameters and returns a matrix containing their sum. If the addition is not possible return an empty matrix.

 

Expected Time Complexity: O(n1 * m1)
Expected Auxiliary Space: O(n1 * m1) for the resultant matrix only. 

 

Constraints:
1 <= n1, m1, n2, m2 <= 30
0 <= Ai, Bi <= 100
  
  
  /*===========================================================================================================*/
  
  
  class Solution
{   
public:
    vector<vector<int> > sumMatrix( const vector<vector<int> >& A, const vector<vector<int> >& B)
    {
        // code here
        vector<vector<int> >arr;
        if(A.size()!=B.size() || A[0].size()!=B[0].size())
        {
            vector<vector<int> >ans(1,vector<int>(1));
            ans[0][0]=-1;
            return ans;
        }
        for(int i=0;i<A.size();i++)
        {
            vector<int> v;
            for(int j=0;j<A[i].size();j++) // Here you wrote i++ instead of j++.
            {
                v.push_back(A[i][j]+B[i][j]);
            }
            arr.push_back(v);
        }
        return arr;
    }
};


/*======================================================================================================*/


class Solution
{   
public:
    vector<vector<int> > sumMatrix( const vector<vector<int> >& A, const vector<vector<int> >& B)
    {
        int n1 = A.size();
        int m1 = A[0].size();
        int n2 = B.size();
        int m2 = B[0].size();
        // Returning an empty matrix if the addition is not possible.
        if (n1 != n2 or m1 != m2) {
            return vector<vector<int>>();
        }
        
        vector<vector <int>>res(n1, vector<int> (m1)); // Allocating the required memory for the output matrix.
        for(int i=0;i<n1;i++)
            {
                
        
                for(int j=0;j<m1;j++)
                    {
                        res[i][j]=A[i][j]+B[i][j];
                    }
            }
            return res;
    }
};
